Parameters:
   
  ServeramiId:
    Default: ami-0df8c184d5f6ae949
    AllowedValues: [ami-0df8c184d5f6ae949, ami-04b4f1a9cf54c11d0]
    Type: String

  EC2InstanceType:
    Default: t2.micro
    AllowedValues: [t2.micro, t2.small, t1.micro]
    Type: String

  Keypair:
    Type: String
    Default: jan205
    AllowedValues: [jan2 ,nov11, jan205]
   
  




Resources:


  Server1:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: !Ref ServeramiId
      InstanceType: !Ref EC2InstanceType
      KeyName: !Ref Keypair

